migrated ci/ci.sh stuff to the travis.yml script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,22 +1,78 @@
 services:
   - mysql
 language: php
-php:
-  - '7.2'
-  - '7.3'
-  - '7.4'
+.steps:
+  - &lint_syntax |
+      echo "------------------------"
+      echo "Checking for PHP syntax errors"
+      failSyntax=false;
+      if find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
+      if find . -type f -name "*.inc" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
+      if $failSyntax; then
+          exit 1;
+      fi
+  - &lint_style |
+      echo "------------------------"
+      echo "Checking for PHP styling (PSR2) issues"
+      composer global require "squizlabs/php_codesniffer=3.*"
+      $HOME/.config/composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full .
+  - &build_test |
+      echo "------------------------"
+      echo "Checking build and tests"
+      echo "------------------------"
+      echo "Build openemr (mimick standard build steps for production package)"
+      composer install
+      npm install
+      npm run build
+      composer global require phing/phing
+      $HOME/.config/composer/vendor/bin/phing vendor-clean
+      $HOME/.config/composer/vendor/bin/phing assets-clean
+      composer global remove phing/phing
+      composer dump-autoload -o
+      rm -fr node_modules
+      echo "------------------------"
+      echo "Also build ccdaservice to allow ccdaservice testing (this step is not part of production build)"
+      cd ccdaservice
+      npm install
+      cd ../
+      echo "------------------------"
+      echo "Install/configure active openemr instance"
+      chmod 666 sites/default/sqlconf.php
+      sudo chown -R www-data:www-data sites/default/documents
+      sed -e 's@^exit;@ @' < contrib/util/installScripts/InstallerAuto.php > contrib/util/installScripts/InstallerAutoTemp.php
+      php -f contrib/util/installScripts/InstallerAutoTemp.php
+      rm -f contrib/util/installScripts/InstallerAutoTemp.php
+      echo "------------------------"
+      echo "Turn on the api to allow api testing"
+      mysql -u openemr --password="openemr" -h localhost -e "UPDATE globals SET gl_value = 1 WHERE gl_name = 'rest_api'" openemr
+      echo "------------------------"
+      echo "Run phpunit testing"
+      composer global require "phpunit/phpunit=8.*"
+      $HOME/.config/composer/vendor/bin/phpunit --testdox
 before_install:
   - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
-env:
-  - CI_JOB=lint_syntax
-  - CI_JOB=build_test
-  - CI_JOB=lint_style
-matrix:
-  exclude:
-    - php: '7.2'
-      env: CI_JOB=lint_style
-    - php: '7.3'
-      env: CI_JOB=lint_style
-before_script: echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
-script:
-  - bash ci/ci.sh --dir ./
+before_script:
+  - echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
+jobs:
+  include:
+    - env: CI_JOB=lint_syntax
+      php: '7.2'
+      script: *lint_syntax
+    - env: CI_JOB=lint_syntax
+      php: '7.3'
+      script: *lint_syntax
+    - env: CI_JOB=lint_syntax
+      php: '7.4'
+      script: *lint_syntax
+    - env: CI_JOB=build_test
+      php: '7.2'
+      script: *build_test
+    - env: CI_JOB=build_test
+      php: '7.3'
+      script: *build_test
+    - env: CI_JOB=build_test
+      php: '7.4'
+      script: *build_test
+    - env: CI_JOB=lint_style
+      php: '7.4'
+      script: *lint_style
