fix(shell): address SC2250
Reduce the error count by 757.

diff --git a/docker/library/dockers/dev-php-fpm/data/docker-php-ext-install b/docker/library/dockers/dev-php-fpm/data/docker-php-ext-install
--- a/docker/library/dockers/dev-php-fpm/data/docker-php-ext-install
+++ b/docker/library/dockers/dev-php-fpm/data/docker-php-ext-install
@@ -2,9 +2,9 @@
 set -e
 
 # prefer user supplied CFLAGS, but default to our PHP_CFLAGS
-: ${CFLAGS:=$PHP_CFLAGS}
-: ${CPPFLAGS:=$PHP_CPPFLAGS}
-: ${LDFLAGS:=$PHP_LDFLAGS}
+: ${CFLAGS:=${PHP_CFLAGS}}
+: ${CPPFLAGS:=${PHP_CPPFLAGS}}
+: ${LDFLAGS:=${PHP_LDFLAGS}}
 export CFLAGS CPPFLAGS LDFLAGS
 
 srcExists=
@@ -12,7 +12,7 @@ if [ -d /usr/src/php ]; then
 	srcExists=1
 fi
 docker-php-source extract
-if [ -z "$srcExists" ]; then
+if [ -z "${srcExists}" ]; then
 	touch /usr/src/php/.docker-delete-me
 fi
 
@@ -42,19 +42,19 @@ usage() {
 }
 
 opts="$(getopt -o 'h?j:' --long 'help,jobs:' -- "$@" || { usage >&2 && false; })"
-eval set -- "$opts"
+eval set -- "${opts}"
 
 j=1
 while true; do
 	flag="$1"
 	shift
-	case "$flag" in
+	case "${flag}" in
 		--help|-h|'-?') usage && exit 0 ;;
 		--jobs|-j) j="$1" && shift ;;
 		--) break ;;
 		*)
 			{
-				echo "error: unknown flag: $flag"
+				echo "error: unknown flag: ${flag}"
 				usage
 			} >&2
 			exit 1
@@ -64,19 +64,19 @@ done
 
 exts=
 for ext; do
-	if [ -z "$ext" ]; then
+	if [ -z "${ext}" ]; then
 		continue
 	fi
-	if [ ! -d "$ext" ]; then
-		echo >&2 "error: $PWD/$ext does not exist"
+	if [ ! -d "${ext}" ]; then
+		echo >&2 "error: ${PWD}/${ext} does not exist"
 		echo >&2
 		usage >&2
 		exit 1
 	fi
-	exts="$exts $ext"
+	exts="${exts} ${ext}"
 done
 
-if [ -z "$exts" ]; then
+if [ -z "${exts}" ]; then
 	usage >&2
 	exit 1
 fi
@@ -87,34 +87,34 @@ if [ -e /lib/apk/db/installed ]; then
 fi
 
 apkDel=
-if [ "$pm" = 'apk' ]; then
-	if [ -n "$PHPIZE_DEPS" ]; then
+if [ "${pm}" = 'apk' ]; then
+	if [ -n "${PHPIZE_DEPS}" ]; then
 		if apk info --installed .phpize-deps-configure > /dev/null; then
 			apkDel='.phpize-deps-configure'
 		elif ! apk info --installed .phpize-deps > /dev/null; then
-			apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS
+			apk add --no-cache --virtual .phpize-deps ${PHPIZE_DEPS}
 			apkDel='.phpize-deps'
 		fi
 	fi
 fi
 
-popDir="$PWD"
-for ext in $exts; do
-	cd "$ext"
-	[ -e Makefile ] || docker-php-ext-configure "$ext"
-	make -j"$j"
-	make -j"$j" install
+popDir="${PWD}"
+for ext in ${exts}; do
+	cd "${ext}"
+	[ -e Makefile ] || docker-php-ext-configure "${ext}"
+	make -j"${j}"
+	make -j"${j}" install
 	find modules \
 		-maxdepth 1 \
 		-name '*.so' \
 		-exec basename '{}' ';' \
 			| xargs -r docker-php-ext-enable
-	make -j"$j" clean
-	cd "$popDir"
+	make -j"${j}" clean
+	cd "${popDir}"
 done
 
-if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
-	apk del $apkDel
+if [ "${pm}" = 'apk' ] && [ -n "${apkDel}" ]; then
+	apk del ${apkDel}
 fi
 
 if [ -e /usr/src/php/.docker-delete-me ]; then
