finalized

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -793,17 +793,17 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
-      - name: E2e testing
-        run: |
-          source ci/ciLibrary.source
-          build_test_e2e
-        if: ${{ success() || failure() }}
+      # - name: E2e testing
+      #   run: |
+      #     source ci/ciLibrary.source
+      #     build_test_e2e
+      #   if: ${{ success() || failure() }}
 
-      - name: Api testing
-        run: |
-          source ci/ciLibrary.source
-          build_test_api
-        if: ${{ success() || failure() }}
+      # - name: Api testing
+      #   run: |
+      #     source ci/ciLibrary.source
+      #     build_test_api
+      #   if: ${{ success() || failure() }}
 
       - name: Fixtures testing
         run: |
