feat: Add e2e testRigor tests
E2e tests for covering the main functionalities

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,7 +2,7 @@ name: Test
 
 on:
   push:
-    branches: [ master ]
+    branches: [ master , feat-add-e2e-tests-7801 ]
   pull_request:
     branches: [ master ]
 
@@ -10,7 +10,6 @@ permissions:
   contents: read
 
 jobs:
-
   build_apache_81_114:
     name: PHP 8.1 - Apache - MariaDB 11.4
     runs-on: ubuntu-22.04
@@ -33,7 +32,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20'
-
+          
       - name: Main build
         run: |
           source ci/ciLibrary.source
@@ -60,6 +59,32 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: Setup ngrok and install jq
+        env:
+          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
+        run: |
+          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
+            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
+            && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
+            | sudo tee /etc/apt/sources.list.d/ngrok.list \
+            && sudo apt update \
+            && sudo apt install ngrok
+
+          ngrok config add-authtoken $NGROK_AUTHTOKEN
+          
+          sudo apt install -y jq
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+          TEST_SUITE_ID: ${{secrets.OPENEMR_TEST_SUITE_ID}}
+          AUTH_TOKEN: ${{secrets.OPENEMR_AUTH_TOKEN}}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -153,6 +178,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -249,6 +282,14 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
@@ -340,6 +381,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -435,6 +484,14 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
@@ -526,6 +583,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -621,12 +686,20 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
           build_test_e2e
         if: ${{ success() || failure() }}
-
+      
       - name: Api testing
         run: |
           source ci/ciLibrary.source
@@ -712,6 +785,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -807,6 +888,14 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
@@ -898,6 +987,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -993,6 +1090,14 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
@@ -1084,6 +1189,14 @@ jobs:
         run: |
           source ci/ciLibrary.source
           build_test_unit
+        if: ${{ success() || failure() }}
+
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
         if: ${{ success() || failure() }}
 
       - name: E2e testing
@@ -1179,6 +1292,14 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
+        run: |
+          source ci/ciLibrary.source
+          build_testrigor_tests
+        if: ${{ success() || failure() }}
+
       - name: E2e testing
         run: |
           source ci/ciLibrary.source
@@ -1223,7 +1344,7 @@ jobs:
 
 
   build_nginx_84:
-    name: PHP 8.4 - Nginx - MariaDB 11.4
+    name: PHP 8.4 - Nginx - MariaDB 11.4 (skipping E2e testing at this time)
     runs-on: ubuntu-22.04
     env:
       DOCKER_DIR: nginx_84
@@ -1273,11 +1394,20 @@ jobs:
           build_test_unit
         if: ${{ success() || failure() }}
 
-      - name: E2e testing
+      - name: testRigor testing
+        env:
+          WORKSPACE_DIR: ${{ github.workspace }}
         run: |
           source ci/ciLibrary.source
-          build_test_e2e
+          build_testrigor_tests
         if: ${{ success() || failure() }}
+
+      - name: E2e testing (skipping at this time for PHP 8.4-dev)
+        run: |
+           echo "SKIPPING THIS TEST FOR NOW UNTIL IT STARTS WORKING IN FUTURE FOR PHP 8.4-dev"
+#          source ci/ciLibrary.source
+#          build_test_e2e
+#        if: ${{ success() || failure() }}
 
       - name: Api testing
         run: |
