more

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,8 +8,38 @@ on:
 
 jobs:
 
+  npm_build_win:
+    name: NPM only install - Windows Server 2022 - NodeJS 16
+    runs-on: windows-2022
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install npm package
+        uses: actions/setup-node@v1
+        with:
+          node-version: '16'
+
+      - name: Main npm Build
+        run: |
+          failTest=false
+          npm install || failTest=true
+          #npm run build || failTest=true
+          if $failTest; then
+            exit 1
+          fi
+
+      - name: CCDA npm Build
+        run: |
+          failTest=false
+          cd ccdaservice || failTest=true
+          npm install || failTest=true
+          cd ../ || failTest=true
+          if $failTest; then
+            exit 1
+          fi
+
   npm_build_macos:
-    name: NPM only build - MacOS Big Sur - NodeJS 16
+    name: NPM only install - MacOS Big Sur - NodeJS 16
     runs-on: macos-11
     steps:
       - uses: actions/checkout@v2
@@ -23,7 +53,7 @@ jobs:
         run: |
           failTest=false
           npm install || failTest=true
-          npm run build || failTest=true
+          #npm run build || failTest=true
           if $failTest; then
             exit 1
           fi
